# Generated by Django 5.2.4 on 2026-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_active_listings_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Optional WhatsApp contact number', max_length=32),
        ),
    ]
