# Generated by Django 5.2.4 on 2026-02-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_company_logo_profile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_color',
            field=models.CharField(default='#0d6efd', help_text='Hex color used for profile accents, e.g. #0d6efd', max_length=7),
        ),
    ]
