# Generated by Django 5.2.4 on 2026-02-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_transactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='responses_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
