# Generated by Django 5.2.4 on 2026-02-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_completed_transactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_description',
            field=models.TextField(blank=True, help_text='Business description or extended bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Certifications or accreditations (comma separated or list)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, help_text='Primary specialization or services offered', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='why_choose',
            field=models.TextField(blank=True, help_text='Short note telling customers why they should choose this seller'),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_in_business',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Years in business (numeric)', null=True),
        ),
    ]
