# Generated by Django 5.2.4 on 2026-03-02 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_business_description_profile_certifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_username', models.CharField(blank=True, max_length=150, null=True)),
                ('new_username', models.CharField(blank=True, max_length=150, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
