# Generated by Django 5.2.4 on 2026-10-08 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def publish_existing(apps, schema_editor):
    # Reviews written before moderation existed were already public; keep them that way.
    apps.get_model('users', 'Review').objects.update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_verify_existing_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting moderation'), ('approved', 'Published'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.RunPython(publish_existing, migrations.RunPython.noop),
    ]
