# Generated by Django 5.2.4 on 2026-10-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverzone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverreview',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverReview',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
