# Generated by Django 5.2.4 on 2026-10-08 20:40

import django.db.models.deletion
import driverzone.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driverzone', '0002_remove_legacy_scaffold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('languages', models.CharField(default='English', max_length=120)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('license_number', models.CharField(max_length=40)),
                ('license_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Staff can suspend a driver')),
                ('city', models.CharField(default='Lagos', max_length=60)),
                ('vehicle_make', models.CharField(blank=True, max_length=40)),
                ('vehicle_model', models.CharField(blank=True, max_length=60)),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=30)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_class', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort')], default='economy', max_length=10)),
                ('offers_chauffeur', models.BooleanField(default=True, help_text="Will drive the customer's own car")),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('4500'), max_digits=10)),
                ('is_online', models.BooleanField(default=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(default=0)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_simulated', models.BooleanField(default=False, help_text='Demo driver: movement is simulated along routes')),
                ('rating_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('trips_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating_avg'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=driverzone.models._trip_number, editable=False, max_length=16, unique=True)),
                ('kind', models.CharField(choices=[('ride', 'Ride'), ('chauffeur', 'Chauffeur (your car)')], default='ride', max_length=10)),
                ('vehicle_class', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort')], default='economy', max_length=10)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_address', models.CharField(blank=True, max_length=255)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('route', models.JSONField(blank=True, default=list, help_text='[[lat, lng], …] along the road')),
                ('approach_route', models.JSONField(blank=True, default=list, help_text='Driver start → pickup')),
                ('distance_m', models.PositiveIntegerField(default=0)),
                ('duration_s', models.PositiveIntegerField(default=0)),
                ('approach_s', models.PositiveIntegerField(default=0)),
                ('hours', models.PositiveSmallIntegerField(default=0, help_text='Chauffeur bookings')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('surge', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3)),
                ('fare_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fare_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash or transfer to the driver'), ('demo', 'Demo payment')], default='cash', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Finding a driver'), ('accepted', 'Driver on the way'), ('arrived', 'Driver has arrived'), ('in_progress', 'On trip'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_driver', 'No driver found')], db_index=True, default='requested', max_length=12)),
                ('simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=10)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='driverzone.driverprofile')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('compliments', models.CharField(blank=True, max_length=200)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('tip', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='driverzone.trip')),
            ],
        ),
    ]
