# Generated by Django 5.2.4 on 2026-10-06 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-order__created_at', 'id']},
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (9am – 12pm)'), ('afternoon', 'Afternoon (12pm – 3pm)'), ('evening', 'Late afternoon (3pm – 6pm)')], max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inspection_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inspection_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('', 'No refund'), ('requested', 'Refund processing'), ('refunded', 'Deposit refunded')], max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('reserved', 'Reserved — awaiting seller'), ('scheduled', 'Inspection scheduled'), ('completed', 'Purchase completed'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('demo', 'Demo payment')], default='paystack', max_length=20),
        ),
    ]
