# Generated by Django 5.2.4 on 2026-10-08 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_reviewed(apps, schema_editor):
    from django.utils import timezone
    apps.get_model('cars', 'CarImage').objects.update(reviewed_at=timezone.now(), created_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_order_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carimage',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carimage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(mark_existing_reviewed, migrations.RunPython.noop),
    ]
