# Generated by Django 5.2.4 on 2026-10-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='accessoryimage',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='accessoryreview',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='order',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='accessoryattribute',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='accessoryreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='AccessoryImage',
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='AccessoryAttribute',
        ),
        migrations.DeleteModel(
            name='AccessoryReview',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
