"""Demo catalogue for the parts store. Prices are realistic Lagos street prices (2026, ₦).

Each product names a `photo` type; `cas/seed/part_photos.json` maps photo types to curated,
freely licensed Wikimedia Commons photos. `fits` uses the same makes/models as the car listings
so "fits my car" works across the site; `universal` items fit any car.
"""

CATEGORIES = [
    # name, slug, icon, blurb
    ('Tyres & wheels', 'tyres-wheels', 'tyre', 'Tyres for every season and road, plus alloy wheels.'),
    ('Batteries', 'batteries', 'battery', 'Maintenance-free and AGM batteries with warranty.'),
    ('Brakes', 'brakes', 'disc', 'Pads, discs and fluid for confident stopping.'),
    ('Oils & fluids', 'oils-fluids', 'droplet', 'Engine oil, coolant and transmission fluid.'),
    ('Filters', 'filters', 'filter', 'Oil, air and cabin filters for routine service.'),
    ('Engine & ignition', 'engine-ignition', 'gear', 'Spark plugs, belts and service parts.'),
    ('Lighting', 'lighting', 'bulb', 'LED and halogen bulbs, headlamps and fog lights.'),
    ('Electronics', 'electronics', 'cpu', 'Dash cams, chargers, stereos and parking aids.'),
    ('Interior', 'interior', 'seat', 'Seat covers, floor mats and comfort upgrades.'),
    ('Exterior & care', 'exterior-care', 'palette', 'Wipers, covers, wax and cleaning.'),
    ('Tools & safety', 'tools-safety', 'shield', 'Jump starters, jacks and emergency kit.'),
]

VENDORS = [
    # email local part, first, last, shop, city, state, years, about
    ('ladipoparts', 'Emeka', 'Nwankwo', 'Ladipo Genuine Parts', 'Mushin', 'Lagos', 12,
     'Genuine and OEM-grade Toyota, Lexus and Honda parts from Ladipo market, with invoices and warranty.'),
    ('tyreworld', 'Bisi', 'Adewale', 'TyreWorld Nigeria', 'Ikeja', 'Lagos', 9,
     'Tyres, batteries and wheels with free fitting advice. Authorised Michelin and Bridgestone stockist.'),
    ('garkiautos', 'Sani', 'Abubakar', 'Garki Auto Supplies', 'Garki', 'FCT', 7,
     'Abuja supplier of service parts, fluids and filters for German and Japanese cars.'),
    ('gadgetdrive', 'Ifeoma', 'Chukwu', 'GadgetDrive', 'Victoria Island', 'Lagos', 4,
     'Car electronics and accessories: dash cams, chargers, smart stereos and interior upgrades.'),
]

TOYOTA_SEDANS = ['Toyota Camry 2018-2024', 'Toyota Corolla 2019-2024']
TOYOTA_SUVS = ['Toyota RAV4 2019-2024', 'Toyota Highlander 2020-2024', 'Toyota Venza 2021-2024']
LEXUS = ['Lexus RX 350 2016-2022', 'Lexus ES 350 2019-2024', 'Lexus RX 450h 2016-2022']
HONDA = ['Honda Accord 2018-2022', 'Honda Civic 2016-2021', 'Honda CR-V 2017-2022', 'Honda Pilot 2016-2022']
KOREAN = ['Hyundai Elantra 2021-2024', 'Hyundai Tucson 2022-2024', 'Kia Sportage 2022-2024', 'Kia Sorento 2021-2024']
GERMAN = ['Mercedes-Benz C 300 2015-2023', 'Mercedes-Benz E 350 2017-2023', 'Mercedes-Benz GLE 450 2019-2024',
          'BMW 330i 2019-2024', 'BMW X3 2018-2024', 'BMW X5 2019-2024']

# vendor index, category slug, brand, name, part_type, price, was, stock, sku, warranty, short, specs, fits/universal, photo
P = [
    # --- Tyres & wheels
    (1, 'tyres-wheels', 'Michelin', 'Primacy 4 205/55 R16 tyre', 'aftermarket', 98000, 112000, 24, 'MIC-P4-2055516', 24,
     'Quiet, long-wearing touring tyre with excellent wet braking.',
     {'Size': '205/55 R16', 'Load index': '91', 'Speed rating': 'V', 'Season': 'All year'},
     ['Toyota Corolla 2019-2024', 'Honda Civic 2016-2021', 'Hyundai Elantra 2021-2024'], 'tyre'),
    (1, 'tyres-wheels', 'Bridgestone', 'Dueler H/T 684 265/65 R17 tyre', 'aftermarket', 168000, None, 16, 'BS-DHT-2656517', 24,
     'Highway-terrain SUV tyre built for Nigerian roads.',
     {'Size': '265/65 R17', 'Load index': '112', 'Speed rating': 'S', 'Pattern': 'Highway terrain'},
     ['Toyota Hilux 2016-2024', 'Toyota Land Cruiser Prado 2010-2023', 'Lexus GX 460 2010-2023'], 'tyre'),
    (1, 'tyres-wheels', 'Michelin', 'Pilot Sport 4 SUV 235/55 R19 tyre', 'aftermarket', 245000, 268000, 12, 'MIC-PS4S-2355519', 24,
     'Sporty grip and precise handling for premium SUVs.',
     {'Size': '235/55 R19', 'Load index': '105', 'Speed rating': 'Y', 'Season': 'Summer'},
     ['Lexus RX 350 2016-2022', 'Toyota Highlander 2020-2024', 'Mercedes-Benz GLC 300 2016-2025', 'Kia Sorento 2021-2024'], 'tyre'),
    (1, 'tyres-wheels', 'Dunlop', 'SP Sport LM705 215/55 R17 tyre', 'aftermarket', 89500, None, 30, 'DUN-LM705-2155517', 12,
     'Comfortable everyday tyre for mid-size sedans.',
     {'Size': '215/55 R17', 'Load index': '94', 'Speed rating': 'V'},
     ['Toyota Camry 2018-2024', 'Honda Accord 2018-2022', 'Nissan Altima 2019-2024'], 'tyre'),
    (1, 'tyres-wheels', 'Hankook', 'Dynapro HP2 235/65 R18 tyre', 'aftermarket', 132000, 145000, 18, 'HK-RA33-2356518', 12,
     'All-season SUV tyre with low road noise.',
     {'Size': '235/65 R18', 'Load index': '106', 'Speed rating': 'H'},
     ['Toyota RAV4 2019-2024', 'Lexus RX 350 2016-2022', 'Honda Pilot 2016-2022', 'Ford Explorer 2020-2024'], 'tyre'),
    (1, 'tyres-wheels', 'Toyota Genuine', '18-inch alloy wheel (single)', 'genuine', 295000, None, 4, 'TY-4261106A10', 12,
     'Factory 5-spoke alloy, replaces a damaged rim.',
     {'Diameter': '18 in', 'Width': '7.5 J', 'Bolt pattern': '5x114.3', 'Finish': 'Silver'},
     ['Toyota Camry 2018-2024', 'Toyota RAV4 2019-2024'], 'alloy'),

    # --- Batteries
    (1, 'batteries', 'Varta', 'Blue Dynamic 70Ah battery', 'aftermarket', 118000, 129000, 20, 'VAR-E43-570', 18,
     'Maintenance-free starter battery for mid-size cars.',
     {'Capacity': '70Ah', 'Cold cranking': '640 A', 'Voltage': '12 V', 'Terminal layout': 'Right positive'},
     TOYOTA_SEDANS + HONDA[:2] + ['Nissan Altima 2019-2024', 'Hyundai Elantra 2021-2024'], 'battery'),
    (1, 'batteries', 'Bosch', 'S5 AGM 80Ah start-stop battery', 'aftermarket', 189000, None, 10, 'BOS-S5A11', 24,
     'AGM battery for cars with start-stop and heavy electrics.',
     {'Capacity': '80Ah', 'Cold cranking': '800 A', 'Technology': 'AGM', 'Voltage': '12 V'},
     GERMAN + ['Land Rover Range Rover Sport 2014-2024'], 'battery'),
    (0, 'batteries', 'Toyota Genuine', 'Maintenance-free battery 75D23L', 'genuine', 132000, None, 8, 'TY-28800-YZZJT', 12,
     'Original-spec Toyota battery with sealed casing.',
     {'Capacity': '65Ah', 'JIS size': '75D23L', 'Voltage': '12 V'},
     TOYOTA_SEDANS + TOYOTA_SUVS + ['Toyota Sienna 2011-2024'], 'battery'),
    (1, 'batteries', 'Exide', 'Mega Start 100Ah heavy-duty battery', 'aftermarket', 165000, 178000, 14, 'EXI-EA1000', 18,
     'High-capacity battery for big SUVs and pickups.',
     {'Capacity': '100Ah', 'Cold cranking': '900 A', 'Voltage': '12 V'},
     ['Toyota Land Cruiser 2008-2025', 'Toyota Hilux 2016-2024', 'Lexus GX 460 2010-2023', 'Lexus LX 570 2008-2021', 'Ford Ranger 2019-2024'], 'battery'),

    # --- Brakes
    (0, 'brakes', 'Toyota Genuine', 'Front brake pad set', 'genuine', 38500, None, 30, 'TY-04465-06090', 6,
     'Original Toyota pads: quiet, low dust, perfect fit.',
     {'Axle': 'Front', 'Pieces': '4 pads + shims', 'Wear sensor': 'Included'},
     TOYOTA_SEDANS + ['Toyota Venza 2021-2024'], 'brakepads'),
    (2, 'brakes', 'Brembo', 'Ceramic front brake pads', 'aftermarket', 46000, 52000, 22, 'BRE-P50069', 12,
     'Low-dust ceramic pads for German sedans and SUVs.',
     {'Axle': 'Front', 'Compound': 'Ceramic', 'Pieces': '4'},
     ['Mercedes-Benz C 300 2015-2023', 'Mercedes-Benz E 350 2017-2023', 'Mercedes-Benz GLC 300 2016-2025'], 'brakepads'),
    (0, 'brakes', 'Akebono', 'ProACT ceramic brake pads (front)', 'aftermarket', 34000, None, 26, 'AKE-ACT1324', 12,
     'Japanese OE supplier pads: smooth and quiet.',
     {'Axle': 'Front', 'Compound': 'Ceramic'},
     LEXUS + ['Toyota Highlander 2020-2024', 'Toyota Sienna 2011-2024'], 'brakepads'),
    (2, 'brakes', 'Bosch', 'QuietCast front brake pads', 'aftermarket', 29500, 33000, 40, 'BOS-BC1210', 12,
     'Everyday pads with rubber shims to cut noise.',
     {'Axle': 'Front', 'Compound': 'Semi-metallic'},
     HONDA + KOREAN, 'brakepads'),
    (0, 'brakes', 'Toyota Genuine', 'Front brake disc (pair)', 'genuine', 72000, None, 10, 'TY-43512-06190', 12,
     'Original vented discs, sold as a pair.',
     {'Axle': 'Front', 'Diameter': '296 mm', 'Type': 'Vented', 'Quantity': 'Pair'},
     TOYOTA_SEDANS, 'brakedisc'),
    (2, 'brakes', 'ATE', 'Front brake disc pair', 'aftermarket', 98000, 109000, 8, 'ATE-24.0130-0206', 12,
     'German-made discs with anti-corrosion coating.',
     {'Axle': 'Front', 'Diameter': '330 mm', 'Type': 'Vented, coated'},
     ['Mercedes-Benz C 300 2015-2023', 'BMW 330i 2019-2024', 'BMW X3 2018-2024'], 'brakedisc'),
    (2, 'brakes', 'Castrol', 'React SRA DOT 4 brake fluid 1L', 'aftermarket', 9500, None, 60, 'CAS-DOT4-1L', 0,
     'High boiling-point brake fluid for ABS systems.',
     {'Spec': 'DOT 4', 'Volume': '1 litre'}, True, 'brakefluid'),

    # --- Oils & fluids
    (2, 'oils-fluids', 'Mobil 1', 'ESP 5W-30 full synthetic oil 5L', 'aftermarket', 68000, 74000, 35, 'MOB-ESP-5W30-5', 0,
     'Approved for modern petrol and diesel engines with DPF.',
     {'Viscosity': '5W-30', 'Volume': '5 litres', 'Approvals': 'MB 229.52, BMW LL-04, VW 504/507'},
     GERMAN, 'engineoil'),
    (0, 'oils-fluids', 'Toyota Genuine', 'Motor oil 0W-20 full synthetic 4L', 'genuine', 42000, None, 40, 'TY-00279-0WQTE', 0,
     'Factory-fill oil for Toyota and Lexus engines.',
     {'Viscosity': '0W-20', 'Volume': '4 litres', 'Spec': 'API SP / ILSAC GF-6'},
     TOYOTA_SEDANS + TOYOTA_SUVS + LEXUS, 'engineoil'),
    (2, 'oils-fluids', 'Castrol', 'EDGE 5W-40 full synthetic 4L', 'aftermarket', 49500, None, 50, 'CAS-EDGE-5W40-4', 0,
     'Titanium-strengthened oil for high-performance engines.',
     {'Viscosity': '5W-40', 'Volume': '4 litres'}, True, 'engineoil'),
    (2, 'oils-fluids', 'Shell', 'Helix HX7 10W-40 semi-synthetic 4L', 'aftermarket', 32000, 36000, 70, 'SHL-HX7-10W40', 0,
     'Value semi-synthetic oil for older and high-mileage engines.',
     {'Viscosity': '10W-40', 'Volume': '4 litres'}, True, 'engineoil'),
    (2, 'oils-fluids', 'Prestone', 'Coolant & antifreeze 50/50 4L', 'aftermarket', 14500, None, 80, 'PRE-AF2100', 0,
     'Ready-to-use coolant that protects against overheating.',
     {'Type': 'Pre-mixed 50/50', 'Volume': '4 litres'}, True, 'coolant'),
    (0, 'oils-fluids', 'Toyota Genuine', 'ATF WS automatic transmission fluid 4L', 'genuine', 46000, None, 18, 'TY-08886-02305', 0,
     'World Standard ATF for Toyota and Lexus automatic gearboxes.',
     {'Type': 'ATF WS', 'Volume': '4 litres'},
     TOYOTA_SEDANS + TOYOTA_SUVS + LEXUS, 'atf'),

    # --- Filters
    (0, 'filters', 'Toyota Genuine', 'Oil filter 04152-YZZA1', 'genuine', 6500, None, 120, 'TY-04152-YZZA1', 0,
     'Cartridge oil filter for Toyota and Lexus 2.5 and 3.5 engines.',
     {'Type': 'Cartridge', 'Includes': 'O-rings'},
     TOYOTA_SEDANS + TOYOTA_SUVS + LEXUS, 'oilfilter'),
    (2, 'filters', 'MANN-FILTER', 'Oil filter HU 7020 z', 'aftermarket', 12500, None, 60, 'MANN-HU7020Z', 0,
     'German OE-quality filter for Mercedes-Benz engines.',
     {'Type': 'Cartridge'}, ['Mercedes-Benz C 300 2015-2023', 'Mercedes-Benz E 350 2017-2023', 'Mercedes-Benz GLC 300 2016-2025'], 'oilfilter'),
    (2, 'filters', 'Bosch', 'Spin-on oil filter 3330', 'aftermarket', 7500, 8500, 90, 'BOS-3330', 0,
     'Premium spin-on filter for Japanese and Korean engines.',
     {'Type': 'Spin-on'}, HONDA + KOREAN + ['Nissan Altima 2019-2024'], 'oilfilter'),
    (0, 'filters', 'Toyota Genuine', 'Engine air filter', 'genuine', 14500, None, 50, 'TY-17801-0V020', 0,
     'Factory air filter: keeps dust out of the engine.',
     {'Type': 'Panel'}, TOYOTA_SEDANS + TOYOTA_SUVS, 'airfilter'),
    (2, 'filters', 'K&N', 'High-flow washable air filter', 'aftermarket', 58000, 64000, 12, 'KN-33-2443', 120,
     'Reusable cotton air filter for more airflow; lasts the life of the car.',
     {'Type': 'Washable cotton', 'Service interval': 'Clean every 80,000 km'},
     ['Toyota Camry 2018-2024', 'Lexus ES 350 2019-2024', 'Toyota RAV4 2019-2024'], 'airfilter'),
    (2, 'filters', 'Bosch', 'Activated-carbon cabin air filter', 'aftermarket', 11500, None, 75, 'BOS-6055C', 0,
     'Traps dust, pollen and odours: cleaner AC air in traffic.',
     {'Type': 'Activated carbon'}, TOYOTA_SEDANS + TOYOTA_SUVS + LEXUS + HONDA, 'cabinfilter'),

    # --- Engine & ignition
    (0, 'engine-ignition', 'Denso', 'Iridium TT spark plug (set of 4)', 'aftermarket', 38000, 42000, 25, 'DEN-IK20TT-4', 0,
     'Twin-tip iridium plugs for smoother idle and better economy.',
     {'Quantity': '4', 'Electrode': 'Iridium + platinum'},
     ['Toyota Corolla 2019-2024', 'Toyota Camry 2018-2024', 'Honda Civic 2016-2021', 'Hyundai Elantra 2021-2024'], 'sparkplug'),
    (0, 'engine-ignition', 'NGK', 'Laser Iridium spark plug (set of 6)', 'aftermarket', 72000, None, 15, 'NGK-ILKAR7B11-6', 0,
     'Long-life plugs for V6 engines, 100,000 km interval.',
     {'Quantity': '6', 'Electrode': 'Iridium'},
     ['Toyota Highlander 2020-2024', 'Lexus RX 350 2016-2022', 'Lexus ES 350 2019-2024', 'Honda Pilot 2016-2022'], 'sparkplug'),
    (0, 'engine-ignition', 'Gates', 'Micro-V serpentine drive belt', 'aftermarket', 21500, None, 30, 'GAT-K060865', 12,
     'Quiet, crack-resistant accessory drive belt.',
     {'Ribs': '6', 'Length': '2197 mm'}, TOYOTA_SEDANS + LEXUS, 'belt'),
    (0, 'engine-ignition', 'Monroe', 'OESpectrum front shock absorber (pair)', 'aftermarket', 165000, 182000, 6, 'MON-72528', 24,
     'Restores ride comfort and control on rough roads.',
     {'Axle': 'Front', 'Quantity': 'Pair', 'Type': 'Gas-charged strut'},
     ['Toyota Camry 2018-2024', 'Toyota RAV4 2019-2024', 'Lexus ES 350 2019-2024'], 'shock'),

    # --- Lighting
    (3, 'lighting', 'Philips', 'Ultinon Pro6000 H11 LED bulbs (pair)', 'aftermarket', 64000, 72000, 20, 'PHI-11362U60', 60,
     'Up to 230% brighter, road-legal LED low beams.',
     {'Fitting': 'H11', 'Colour temperature': '5800 K', 'Quantity': 'Pair'},
     TOYOTA_SEDANS + ['Toyota RAV4 2019-2024', 'Honda Accord 2018-2022', 'Kia Sportage 2022-2024'], 'ledbulb'),
    (3, 'lighting', 'OSRAM', 'Night Breaker H7 halogen bulbs (pair)', 'aftermarket', 21000, None, 40, 'OSR-64210NB200', 12,
     'Brighter halogen low beam: 200% more light.',
     {'Fitting': 'H7', 'Power': '55 W', 'Quantity': 'Pair'},
     ['Mercedes-Benz C 300 2015-2023', 'BMW 330i 2019-2024', 'Peugeot 3008 2017-2023', 'Volkswagen Tiguan 2017-2023'], 'ledbulb'),
    (0, 'lighting', 'Depo', 'Headlamp assembly (left)', 'aftermarket', 185000, None, 3, 'DEPO-312-11A6L', 6,
     'Direct-fit replacement headlamp, ready to install.',
     {'Side': 'Left (driver)', 'Type': 'Halogen projector'}, ['Toyota Camry 2018-2024'], 'headlamp'),
    (3, 'lighting', 'Hella', 'LED fog light kit', 'accessory', 52000, 59000, 14, 'HEL-FF50', 24,
     'Bright, wide LED fog lights with wiring harness.',
     {'Power': '2 × 12 W', 'Housing': 'IP67 waterproof'}, True, 'foglight'),

    # --- Electronics
    (3, 'electronics', '70mai', 'A800S 4K dash cam with rear camera', 'accessory', 145000, 159000, 18, '70M-A800S-1', 12,
     'Records front and rear in 4K with GPS and parking guard.',
     {'Resolution': '4K front, 1080p rear', 'Storage': 'Up to 128 GB microSD', 'Extras': 'GPS, Wi-Fi app'}, True, 'dashcam'),
    (3, 'electronics', 'Xiaomi', 'Mi dash cam 2K', 'accessory', 54000, None, 30, 'XMI-MJXCJ02', 12,
     'Compact 2K dash cam with night vision and voice control.',
     {'Resolution': '2K (1296p)', 'Screen': '3 in'}, True, 'dashcam'),
    (3, 'electronics', 'Anker', 'PowerDrive 2-port 36W fast car charger', 'accessory', 14500, 17000, 90, 'ANK-A2721', 18,
     'USB-C + USB-A fast charging for phones and tablets.',
     {'Ports': 'USB-C PD + USB-A', 'Output': '36 W total'}, True, 'charger'),
    (3, 'electronics', 'Baseus', 'Magnetic dashboard phone holder', 'accessory', 9500, None, 120, 'BAS-SUGX', 6,
     'Strong magnetic mount that sticks to any dashboard.',
     {'Mount': 'Dashboard / vent', 'Compatibility': 'All phones (plate included)'}, True, 'phoneholder'),
    (3, 'electronics', 'Pioneer', 'DMH-Z5350BT 9-inch Apple CarPlay & Android Auto receiver', 'accessory', 425000, 468000, 6, 'PIO-DMHZ5350', 12,
     'Big-screen stereo with wireless CarPlay and Android Auto.',
     {'Screen': '9 in capacitive', 'Wireless': 'CarPlay, Android Auto, Bluetooth'}, True, 'stereo'),
    (3, 'electronics', 'Steelmate', 'Wireless reverse camera kit', 'accessory', 38000, None, 25, 'STM-RC-W1', 12,
     'Plug-in rear camera with night vision and parking lines.',
     {'Connection': 'Wireless', 'View angle': '170°'}, True, 'reversecam'),
    (3, 'electronics', 'Bosch', 'Parking sensor kit (4 sensors)', 'accessory', 32000, 36000, 20, 'BOS-PS4', 12,
     'Audible warnings as you approach obstacles when reversing.',
     {'Sensors': '4 rear', 'Display': 'Buzzer + LED'}, True, 'parksensor'),

    # --- Interior
    (3, 'interior', 'CarHub Essentials', 'Leather-look seat covers (full set)', 'accessory', 68000, 79000, 22, 'CHE-SC-BLK', 6,
     'Wipe-clean seat covers that protect original upholstery.',
     {'Material': 'PU leather', 'Set': '5 seats', 'Colour': 'Black with grey stitch'}, True, 'seatcover'),
    (3, 'interior', 'WeatherTech', 'All-weather floor mats (front & rear)', 'accessory', 89000, None, 12, 'WT-FL-445', 24,
     'Laser-measured mats that trap water, mud and sand.',
     {'Pieces': '4', 'Material': 'Thermoplastic'},
     ['Toyota Camry 2018-2024', 'Toyota RAV4 2019-2024', 'Lexus RX 350 2016-2022', 'Honda Accord 2018-2022'], 'floormat'),
    (3, 'interior', 'CarHub Essentials', 'Universal rubber floor mats', 'accessory', 18500, 22000, 60, 'CHE-FM-UNI', 0,
     'Trim-to-fit rubber mats for any car.',
     {'Pieces': '4', 'Material': 'Rubber'}, True, 'floormat'),
    (3, 'interior', 'CarHub Essentials', 'Leather steering wheel cover', 'accessory', 9500, None, 80, 'CHE-SWC-38', 0,
     'Better grip and cooler to touch in the sun.',
     {'Diameter': '37–39 cm', 'Material': 'Microfibre leather'}, True, 'steeringcover'),
    (3, 'interior', 'Armor All', 'Windscreen sun shade', 'accessory', 12000, 14500, 70, 'AA-SS-L', 0,
     'Keeps the cabin cooler when parked in the sun.',
     {'Size': 'Large (SUV/sedan)', 'Type': 'Foldable reflective'}, True, 'sunshade'),

    # --- Exterior & care
    (2, 'exterior-care', 'Bosch', 'Aerotwin wiper blade set', 'aftermarket', 26000, 29000, 40, 'BOS-A980S', 0,
     'Flat blades for streak-free wiping in heavy rain.',
     {'Lengths': '650 mm + 400 mm', 'Type': 'Flat beam'},
     TOYOTA_SEDANS + HONDA[:2] + ['Mercedes-Benz C 300 2015-2023'], 'wiper'),
    (2, 'exterior-care', 'Rain-X', 'Latitude water-repellent wipers (pair)', 'aftermarket', 21000, None, 35, 'RX-5079281', 0,
     'Blades with built-in water repellent coating.',
     {'Lengths': '24 in + 18 in'}, TOYOTA_SUVS + LEXUS + KOREAN, 'wiper'),
    (3, 'exterior-care', 'Meguiar’s', 'Ultimate liquid wax 473ml', 'accessory', 24500, 27000, 40, 'MEG-G18216', 0,
     'Long-lasting shine and protection from the sun.',
     {'Volume': '473 ml', 'Type': 'Synthetic polymer wax'}, True, 'wax'),
    (3, 'exterior-care', 'CarHub Essentials', 'Waterproof full car cover', 'accessory', 42000, None, 20, 'CHE-CC-L', 6,
     'Protects paint from sun, dust and rain when parked outside.',
     {'Size': 'Large sedan / mid SUV', 'Material': 'Multi-layer PEVA'}, True, 'carcover'),
    (3, 'exterior-care', 'Chemical Guys', 'Car wash starter kit', 'accessory', 38500, 43000, 18, 'CG-HOL126', 0,
     'Shampoo, mitt, microfibre towels and tyre shine.',
     {'Includes': '6 pieces'}, True, 'carwash'),

    # --- Tools & safety
    (3, 'tools-safety', 'NOCO', 'Boost Plus GB40 1000A jump starter', 'accessory', 125000, 139000, 15, 'NOC-GB40', 12,
     'Start a flat battery in seconds, no second car needed. Doubles as a power bank.',
     {'Peak current': '1000 A', 'Engines': 'Petrol up to 6.0 L, diesel up to 3.0 L'}, True, 'jumpstarter'),
    (1, 'tools-safety', 'CarHub Essentials', 'Heavy-duty jumper cables 4 m', 'accessory', 15500, None, 50, 'CHE-JC-4M', 6,
     'Thick copper cables with insulated clamps.',
     {'Length': '4 m', 'Gauge': '6 AWG'}, True, 'jumpercable'),
    (1, 'tools-safety', 'Michelin', 'Digital tyre inflator 12V', 'accessory', 48000, 55000, 25, 'MIC-12266', 12,
     'Plug into the cigarette lighter and set the pressure; stops automatically.',
     {'Max pressure': '100 PSI', 'Power': '12 V'}, True, 'inflator'),
    (1, 'tools-safety', 'Torin', 'Hydraulic bottle jack 3-ton', 'accessory', 28000, None, 30, 'TOR-T90304', 12,
     'Lifts SUVs and pickups safely for tyre changes.',
     {'Capacity': '3 tonnes', 'Lift range': '194–372 mm'}, True, 'jack'),
    (1, 'tools-safety', 'CarHub Essentials', 'Reflective warning triangle (pair)', 'accessory', 7500, None, 100, 'CHE-WT-2', 0,
     'Required by FRSC: keep two in your boot.',
     {'Standard': 'ECE R27', 'Quantity': '2'}, True, 'triangle'),
    (1, 'tools-safety', 'Kidde', '1 kg car fire extinguisher', 'accessory', 16500, 19000, 60, 'KID-1KG-ABC', 12,
     'Dry-powder extinguisher with bracket. An FRSC requirement.',
     {'Size': '1 kg', 'Class': 'ABC dry powder'}, True, 'extinguisher'),
    (1, 'tools-safety', 'CarHub Essentials', 'Roadside emergency kit', 'accessory', 34000, 39000, 25, 'CHE-RK-01', 6,
     'First-aid kit, tow rope, torch, gloves and reflective vest in one bag.',
     {'Pieces': '24'}, True, 'emergencykit'),
    (1, 'tools-safety', 'Stanley', '1/2-inch socket & wrench set (40 pieces)', 'accessory', 42000, None, 20, 'STA-STMT74183', 12,
     'The essentials for basic repairs and wheel changes.',
     {'Pieces': '40', 'Drive': '1/2 in & 1/4 in'}, True, 'toolkit'),
]

PHOTO_QUERIES = {
    'tyre': ['car tyre new', 'tire tread new', 'Michelin tyre'],
    'alloy': ['alloy wheel car', 'alloy rim'],
    'battery': ['car battery', 'automotive battery 12V'],
    'brakepads': ['disc brake pads car', 'brake pad'],
    'brakedisc': ['brake disc rotor', 'disc brake rotor car'],
    'brakefluid': ['brake fluid bottle', 'DOT 4 brake fluid'],
    'engineoil': ['motor oil bottle', 'engine oil can'],
    'coolant': ['antifreeze coolant bottle', 'coolant reservoir car'],
    'atf': ['automatic transmission fluid', 'transmission fluid bottle'],
    'oilfilter': ['oil filter car', 'spin-on oil filter'],
    'airfilter': ['car air filter', 'engine air filter'],
    'cabinfilter': ['cabin air filter', 'pollen filter car'],
    'sparkplug': ['spark plug', 'iridium spark plug'],
    'belt': ['serpentine belt', 'drive belt car engine'],
    'shock': ['shock absorber car', 'strut assembly'],
    'ledbulb': ['LED headlight bulb', 'H7 bulb halogen', 'car headlight bulb'],
    'headlamp': ['car headlamp assembly', 'headlight car'],
    'foglight': ['fog lamp car', 'fog light car'],
    'dashcam': ['dashcam', 'dash cam car'],
    'charger': ['car charger USB', 'cigarette lighter USB charger'],
    'phoneholder': ['car phone holder', 'smartphone car mount'],
    'stereo': ['car stereo touchscreen', 'Android Auto head unit', 'car radio head unit'],
    'reversecam': ['backup camera car', 'rear view camera car'],
    'parksensor': ['parking sensor bumper', 'parking sensors car'],
    'seatcover': ['car seat cover', 'car seats leather interior'],
    'floormat': ['car floor mat', 'floor mats car'],
    'steeringcover': ['steering wheel cover', 'leather steering wheel'],
    'sunshade': ['windshield sun shade', 'car sunshade'],
    'wiper': ['windscreen wiper blade', 'wiper blade'],
    'wax': ['car wax polish', 'car polish'],
    'carcover': ['car cover', 'covered car tarp'],
    'carwash': ['car wash sponge bucket', 'washing a car'],
    'jumpstarter': ['jump starter portable', 'battery booster pack'],
    'jumpercable': ['jumper cables', 'booster cables'],
    'inflator': ['tire inflator', 'portable air compressor car'],
    'jack': ['bottle jack hydraulic', 'car jack'],
    'triangle': ['warning triangle', 'reflective warning triangle'],
    'extinguisher': ['car fire extinguisher', 'fire extinguisher small'],
    'emergencykit': ['first aid kit car', 'roadside emergency kit'],
    'toolkit': ['socket wrench set', 'socket set'],
}
